date_format: "%Y-%m-%d"

websites:
  - BOOKING
  - TRIPADVISOR
  - GOOGLE
  - EXPEDIA
  - HOLIDAYCHECK

hotels:
  - name: "ananea Castelo Suites"
    aliases: ["ananea", "ananea castelo"]
    booking_url: "https://www.booking.com/hotel/pt/castelo-suites.en-gb.html"
    tripadvisor_url: ""
    google_place_id: ""
    expedia_url: ""
    holidaycheck_url: ""
    zoover_url: ""

  - name: "PortoBay Falésia"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/porto-bay-falesia.en-gb.html"
    tripadvisor_url: ""
    google_place_id: ""
    expedia_url: ""
    holidaycheck_url: ""
    zoover_url: ""

  - name: "Regency Salgados Hotel & Spa"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/regency-salgados-amp-spa.en-gb.html"
    tripadvisor_url: ""
    google_place_id: ""
    expedia_url: ""
    holidaycheck_url: ""
    zoover_url: ""

  - name: "NAU São Rafael Atlântico"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/sao-rafael-suites-all-inclusive.en-gb.html"
    tripadvisor_url: ""
    google_place_id: ""
    expedia_url: ""
    holidaycheck_url: ""
    zoover_url: ""

  - name: "NAU Salgados Dunas Suites"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/westin-salgados-beach-resort-algarve.en-gb.html"
    tripadvisor_url: ""
    google_place_id: ""
    expedia_url: ""
    holidaycheck_url: ""
    zoover_url: ""

  - name: "Vidamar Resort Hotel Algarve"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/vidamar-algarve-hotel.en-gb.html"
    tripadvisor_url: ""
    google_place_id: ""
    expedia_url: ""
    holidaycheck_url: ""
    zoover_url: ""
